-- MySQL Script generated by MySQL Workbench
-- 03/31/23 00:44:46
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tarea16_Grupo05
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tarea16_Grupo05` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Tarea16_Grupo05` ;

-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`Sucursales` (
  `CodigoSucursal` INT NOT NULL AUTO_INCREMENT,
  `DireccionSucursal` VARCHAR(45) NOT NULL,
  `TelefonoSucursal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CodigoSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`Turistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`Turistas` (
  `CodigoTurista` INT NOT NULL AUTO_INCREMENT,
  `NombreTurista` VARCHAR(45) NOT NULL,
  `ApellidoTurista` VARCHAR(45) NOT NULL,
  `DireccionTurista` VARCHAR(80) NOT NULL,
  `TelefonoTurista` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CodigoTurista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`Hoteles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`Hoteles` (
  `CodigoHotel` INT NOT NULL AUTO_INCREMENT,
  `NombreHotel` VARCHAR(45) NOT NULL,
  `DireccionHotel` VARCHAR(45) NOT NULL,
  `CiudadHotel` VARCHAR(45) NOT NULL,
  `TelefonoHotel` VARCHAR(45) NOT NULL,
  `PlazasHotel` INT NOT NULL,
  PRIMARY KEY (`CodigoHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`Estancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`Estancias` (
  `CodigoEstancia` INT NOT NULL AUTO_INCREMENT,
  `Pension` VARCHAR(45) NOT NULL,
  `FechaEntrada` DATE NOT NULL,
  `FechaSalida` DATE NOT NULL,
  `Hoteles_CodigoHotel` INT NOT NULL,
  PRIMARY KEY (`CodigoEstancia`, `Hoteles_CodigoHotel`),
  INDEX `fk_Estancias_Hoteles1_idx` (`Hoteles_CodigoHotel` ASC),
  CONSTRAINT `fk_Estancias_Hoteles1`
    FOREIGN KEY (`Hoteles_CodigoHotel`)
    REFERENCES `Tarea16_Grupo05`.`Hoteles` (`CodigoHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`ViajesContratados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`ViajesContratados` (
  `CodigoViajes` INT NOT NULL AUTO_INCREMENT,
  `Turistas_CodigoTurista` INT NOT NULL,
  `Sucursales_CodigoSucursal` INT NOT NULL,
  `Estancias_CodigoEstancia` INT NOT NULL,
  PRIMARY KEY (`CodigoViajes`, `Turistas_CodigoTurista`, `Sucursales_CodigoSucursal`, `Estancias_CodigoEstancia`),
  INDEX `fk_ViajesContratados_Sucursales_idx` (`Sucursales_CodigoSucursal` ASC),
  INDEX `fk_ViajesContratados_Turistas1_idx` (`Turistas_CodigoTurista` ASC),
  INDEX `fk_ViajesContratados_Estancias1_idx` (`Estancias_CodigoEstancia` ASC),
  CONSTRAINT `fk_ViajesContratados_Sucursales`
    FOREIGN KEY (`Sucursales_CodigoSucursal`)
    REFERENCES `Tarea16_Grupo05`.`Sucursales` (`CodigoSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ViajesContratados_Turistas1`
    FOREIGN KEY (`Turistas_CodigoTurista`)
    REFERENCES `Tarea16_Grupo05`.`Turistas` (`CodigoTurista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ViajesContratados_Estancias1`
    FOREIGN KEY (`Estancias_CodigoEstancia`)
    REFERENCES `Tarea16_Grupo05`.`Estancias` (`CodigoEstancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`Vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`Vuelos` (
  `NumeroVuelo` INT NOT NULL AUTO_INCREMENT,
  `FechaVuelo` DATE NOT NULL,
  `HoraVuelo` TIME NOT NULL,
  `OrigenVuelo` VARCHAR(45) NOT NULL,
  `DestinoVuelo` VARCHAR(45) NOT NULL,
  `PlazasTotales` INT NOT NULL,
  `PlazasTurista` INT NOT NULL,
  PRIMARY KEY (`NumeroVuelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tarea16_Grupo05`.`VuelosTuristicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tarea16_Grupo05`.`VuelosTuristicos` (
  `CodigoVuelo` INT NOT NULL AUTO_INCREMENT,
  `Clase` VARCHAR(20) NOT NULL,
  `Vuelos_NumeroVuelo` INT NOT NULL,
  `ViajesContratados_CodigoViajes` INT NOT NULL,
  PRIMARY KEY (`CodigoVuelo`, `Vuelos_NumeroVuelo`, `ViajesContratados_CodigoViajes`),
  INDEX `fk_VuelosTuristicos_ViajesContratados1_idx` (`ViajesContratados_CodigoViajes` ASC),
  INDEX `fk_VuelosTuristicos_Vuelos1_idx` (`Vuelos_NumeroVuelo` ASC),
  CONSTRAINT `fk_VuelosTuristicos_ViajesContratados1`
    FOREIGN KEY (`ViajesContratados_CodigoViajes`)
    REFERENCES `Tarea16_Grupo05`.`ViajesContratados` (`CodigoViajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VuelosTuristicos_Vuelos1`
    FOREIGN KEY (`Vuelos_NumeroVuelo`)
    REFERENCES `Tarea16_Grupo05`.`Vuelos` (`NumeroVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
